### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by rhymist2000** [anisearch/anisearch.ru#3]
A RSS feed to allow automated search and download as new torrents are added would be great.

**Comment by anisearch** [comment]
Like you wanted, we added the RSS Feed:
https://rss.anisearch.ru

**Comment by rhymist2000** [comment]
Great! Thanks for working in it so quickly.
I intend to use this with Sonarr, but I seem to be having an issue with it. Could it be a format problem? Any ideas?

[Screen Shot 2017-05-20 at 12.31.40 PM.pdf](https://github.com/anisearch/anisearch.ru/files/1016082/Screen.Shot.2017-05-20.at.12.31.40.PM.pdf)

**Comment by anisearch** [comment]
@rhymist2000 fixed, try again

**Comment by rhymist2000** [comment]
You got it, Nice work, @anisearch!

Thanks for the prompt responses! 
Have a good day further.
